# **Cohort Analysis - Customer Analysis**

### **Import the Library**

In [1]:
import pandas as pd

### **Import Data**

In [2]:
df_customer = pd.read_csv('/content/Customer.csv')
df_ecom_sales = pd.read_csv('/content/EcomSales.csv')
df_product = pd.read_csv('/content/Product.csv')
df_region = pd.read_csv('/content/Region.csv')

### **Information of Data**

In [3]:
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17415 entries, 0 to 17414
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      17415 non-null  object
 1   FirstName       17415 non-null  object
 2   LastName        17415 non-null  object
 3   BirthDate       17415 non-null  object
 4   MaritalStatus   17415 non-null  object
 5   Gender          17291 non-null  object
 6   EmailAddress    17415 non-null  object
 7   AnnualIncome    17415 non-null  int64
 8   EducationLevel  17415 non-null  object
 9   Occupation      17415 non-null  object
 10  HomeOwner       17415 non-null  object
dtypes: int64(1), object(10)
memory usage: 1.5+ MB

In [28]:
df_customer['Occupation'].unique()

array(['Professional', 'Management', 'Skilled Manual', 'Clerical',
       'Manual'], dtype=object)

In [5]:
df_ecom_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RowID        51290 non-null  int64
 1   OrderID      51290 non-null  object
 2   OrderDate    51290 non-null  object
 3   CustomerID   51290 non-null  object
 4   Segment      51290 non-null  object
 5   RegionCode   51290 non-null  object
 6   ProductCode  51290 non-null  object
 7   Quantity     51290 non-null  int64
 8   Sales        51290 non-null  int64
 9   Discount     51290 non-null  float64
 10  Profit       51290 non-null  float64
dtypes: float64(2), int64(3), object(6)
memory usage: 4.3+ MB

In [30]:
df_ecom_sales['Segment'].unique()

array(['Corporate', 'Consumer', 'Self-Employed'], dtype=object)

In [6]:
df_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28356 entries, 0 to 28355
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductCode  28356 non-null  object
 1   Product      28356 non-null  object
 2   Category     28356 non-null  object
 3   Subcategory  28356 non-null  object
dtypes: object(4)
memory usage: 886.3+ KB

In [7]:
df_region.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3828 entries, 0 to 3827
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   RegionCode        3828 non-null   object
 1   City              3828 non-null   object
 2   State             3828 non-null   object
 3   Country           3828 non-null   object
 4   Countrylatitude   3828 non-null   float64
 5   Countrylongitude  3828 non-null   float64
 6   Region            3828 non-null   object
 7   Market            3828 non-null   object
dtypes: float64(2), object(6)
memory usage: 239.4+ KB

In [8]:
df_customer.describe().T

,count,mean,std,min,25%,50%,75%,max
AnnualIncome,17415.0,57190.927361,32213.237506,10000.0,30000.0,60000.0,70000.0,170000.0

In [9]:
df_ecom_sales.describe().T

,count,mean,std,min,25%,50%,75%,max
RowID,51290.0,25645.500000,14806.291990,1.0,12823.25,25645.5,38467.75,51290.00
Quantity,51290.0,5.415832,4.908234,1.0,2.00,4.0,7.00,20.00
Sales,51290.0,127.074946,236.074764,2.0,25.00,56.0,132.00,3940.00
Discount,51290.0,0.142908,0.212280,0.0,0.00,0.0,0.20,0.85
Profit,51290.0,20.772346,83.582680,-1746.0,0.00,7.2,25.00,1820.00

In [10]:
df_product.describe().T

             count unique                           top   freq
ProductCode  28356  28356                       P028356      1
Product      28356   3577  One A Day Elderberry Gummies     17
Category     28356      5                     Body care  11548
Subcategory  28356     17            Nail care products   2386

In [11]:
df_region.describe().T

,count,mean,std,min,25%,50%,75%,max
Countrylatitude,3828.0,28.510730,24.018286,-40.900557,20.593684,37.090240,46.227638,61.924110
Countrylongitude,3828.0,-1.314251,70.745155,-106.346771,-66.589730,2.213749,35.243322,174.885971

### **Handling Missing Data**

In [12]:
df_customer.isnull().sum()

CustomerID          0
FirstName           0
LastName            0
BirthDate           0
MaritalStatus       0
Gender            124
EmailAddress        0
AnnualIncome        0
EducationLevel      0
Occupation          0
HomeOwner           0
dtype: int64

There are some missing values in the ‘Gender’ column. However, I will handle them since they are not very important for my analysis, so I will replace them with 'Null' values.

In [13]:
df_customer.isnull().sum()

CustomerID          0
FirstName           0
LastName            0
BirthDate           0
MaritalStatus       0
Gender            124
EmailAddress        0
AnnualIncome        0
EducationLevel      0
Occupation          0
HomeOwner           0
dtype: int64

There are no missing value in the df_customer.

In [14]:
df_ecom_sales.isnull().sum()

RowID          0
OrderID        0
OrderDate      0
CustomerID     0
Segment        0
RegionCode     0
ProductCode    0
Quantity       0
Sales          0
Discount       0
Profit         0
dtype: int64

There are no missing value in the df_ecom_sales.

In [15]:
df_product.isnull().sum()

ProductCode    0
Product        0
Category       0
Subcategory    0
dtype: int64

There are no missing value in the df_product.

In [16]:
df_region.isnull().sum()

RegionCode          0
City                0
State               0
Country             0
Countrylatitude     0
Countrylongitude    0
Region              0
Market              0
dtype: int64

There are no missing value in the df_region.

### **Handling Duplicated Data**

In [17]:
df_customer.duplicated().sum()

np.int64(0)

In [18]:
df_ecom_sales.duplicated().sum()

np.int64(0)

In [19]:
df_product.duplicated().sum()

np.int64(0)

In [20]:
df_region.duplicated().sum()

np.int64(0)

There are no duplicated value in all the DataFrame.

### **Cohort Analysis**

### **Acquisition month for each customer**

In [21]:
# Merge df_customer and df_ecom_sales to link customer information with sales data
df_merged = pd.merge(df_ecom_sales, df_customer, on='CustomerID', how='left')

# Convert 'OrderDate' to datetime objects
df_merged['OrderDate'] = pd.to_datetime(df_merged['OrderDate'])

# Group by CustomerID and find the minimum OrderDate to get the first purchase date for each customer
df_first_purchase = df_merged.groupby('CustomerID')['OrderDate'].min().reset_index()
df_first_purchase.rename(columns={'OrderDate': 'FirstPurchaseDate'}, inplace=True)

# Extract the 'first purchase month' from the minimum OrderDate
df_first_purchase['CohortMonth'] = df_first_purchase['FirstPurchaseDate'].dt.to_period('M')

# Filter df_first_purchase to include only CohortMonth from 2022
df_first_purchase = df_first_purchase[df_first_purchase['CohortMonth'].dt.year == 2022]

display(df_first_purchase.head())

      CustomerID FirstPurchaseDate CohortMonth
2    AA-10315139        2022-09-19     2022-09
3   AA-103151402        2022-03-04     2022-03
7     AA-1031548        2022-08-07     2022-08
8     AA-1031558        2022-12-31     2022-12
12   AA-10375101        2022-06-28     2022-06

In [22]:
# Merge 'CohortMonth' into df_merged (re-run after filtering df_first_purchase)
df_merged = pd.merge(df_merged.drop(columns=['CohortMonth'], errors='ignore'),
                     df_first_purchase[['CustomerID', 'CohortMonth']], on='CustomerID', how='left')

# Extract 'OrderMonth' from 'OrderDate'
df_merged['OrderMonth'] = df_merged['OrderDate'].dt.to_period('M')

# Filter df_merged to only include orders placed in 2022
df_merged = df_merged[df_merged['OrderMonth'].dt.year == 2022]

display(df_merged.head())

,RowID,OrderID,OrderDate,CustomerID,Segment,RegionCode,ProductCode,Quantity,Sales,Discount,...,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,EducationLevel,Occupation,HomeOwner,CohortMonth,OrderMonth
3,28882,IN-2014-SU206651-41899,2022-09-17,SU-206651,Self-Employed,R0003,P000004,4,556,0.0,...,8/4/1988,S,F,christy12@hotmail.com,70000,Bachelors,Professional,N,2022-09,2022-09
16,24294,IN-2014-JM156551-41905,2022-09-23,JM-156551,Corporate,R0003,P000017,15,735,0.0,...,2/3/1994,S,F,jacquelyn20@hotmail.com,70000,Bachelors,Professional,N,2022-09,2022-09
17,29494,IN-2014-LO171701-41906,2022-09-24,LO-171701,Corporate,R0003,P000018,12,336,0.0,...,11/9/1979,M,M,curtis9@hotmail.com,60000,Bachelors,Professional,Y,2022-09,2022-09
18,28265,IN-2014-AH105851-41970,2022-11-27,AH-105851,Consumer,R0003,P000019,6,36,0.0,...,4/21/1981,M,F,lauren41@hotmail.com,100000,Bachelors,Management,Y,NaT,2022-11
26,21399,IN-2014-VW217751-41901,2022-09-19,VW-217751,Corporate,R0004,P000027,8,80,0.0,...,12/24/1992,S,M,clarence32@hotmail.com,30000,Partial College,Clerical,Y,2022-09,2022-09

In [23]:
# Drop rows where CohortMonth is NaT (customers whose first purchase was not in 2022)
df_cohort = df_merged.dropna(subset=['CohortMonth'])

display(df_cohort.head())

,RowID,OrderID,OrderDate,CustomerID,Segment,RegionCode,ProductCode,Quantity,Sales,Discount,...,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,EducationLevel,Occupation,HomeOwner,CohortMonth,OrderMonth
3,28882,IN-2014-SU206651-41899,2022-09-17,SU-206651,Self-Employed,R0003,P000004,4,556,0.0,...,8/4/1988,S,F,christy12@hotmail.com,70000,Bachelors,Professional,N,2022-09,2022-09
16,24294,IN-2014-JM156551-41905,2022-09-23,JM-156551,Corporate,R0003,P000017,15,735,0.0,...,2/3/1994,S,F,jacquelyn20@hotmail.com,70000,Bachelors,Professional,N,2022-09,2022-09
17,29494,IN-2014-LO171701-41906,2022-09-24,LO-171701,Corporate,R0003,P000018,12,336,0.0,...,11/9/1979,M,M,curtis9@hotmail.com,60000,Bachelors,Professional,Y,2022-09,2022-09
26,21399,IN-2014-VW217751-41901,2022-09-19,VW-217751,Corporate,R0004,P000027,8,80,0.0,...,12/24/1992,S,M,clarence32@hotmail.com,30000,Partial College,Clerical,Y,2022-09,2022-09
27,29493,IN-2014-LO171701-41906,2022-09-24,LO-171701,Corporate,R0003,P000028,12,816,0.0,...,11/9/1979,M,M,curtis9@hotmail.com,60000,Bachelors,Professional,Y,2022-09,2022-09

In [25]:
# Calculate MonthSinceFirstPurchase (0-indexed)
df_cohort.loc[:, 'MonthSinceFirstPurchase'] = (df_cohort['OrderMonth'].dt.year - df_cohort['CohortMonth'].dt.year) * 12 + \
                                       (df_cohort['OrderMonth'].dt.month - df_cohort['CohortMonth'].dt.month)

# Group by CohortMonth and MonthSinceFirstPurchase to count unique customers
cohort_counts = df_cohort.groupby(['CohortMonth', 'MonthSinceFirstPurchase'])['CustomerID'].nunique().reset_index()

# Create the pivot table for cohort analysis
cohort_pivot = cohort_counts.pivot_table(index='CohortMonth', columns='MonthSinceFirstPurchase', values='CustomerID')

display(cohort_pivot)

/tmp/ipykernel_27833/1540112921.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cohort.loc[:, 'MonthSinceFirstPurchase'] = (df_cohort['OrderMonth'].dt.year - df_cohort['CohortMonth'].dt.year) * 12 + \

MonthSinceFirstPurchase,0,1,2,3,4,5,6,7,8,9,10,11
CohortMonth,,,,,,,,,,,,
2022-01,252.0,1.0,1.0,4.0,4.0,3.0,4.0,6.0,7.0,4.0,9.0,1.0
2022-02,214.0,4.0,2.0,5.0,1.0,2.0,7.0,5.0,5.0,5.0,3.0,NaN
2022-03,290.0,2.0,5.0,4.0,4.0,9.0,10.0,3.0,7.0,13.0,NaN,NaN
2022-04,258.0,1.0,5.0,2.0,3.0,5.0,3.0,6.0,7.0,NaN,NaN,NaN
2022-05,352.0,7.0,7.0,10.0,8.0,5.0,7.0,13.0,NaN,NaN,NaN,NaN
2022-06,517.0,6.0,17.0,13.0,6.0,6.0,17.0,NaN,NaN,NaN,NaN,NaN
2022-07,292.0,8.0,8.0,4.0,6.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN
2022-08,442.0,13.0,9.0,6.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-09,518.0,9.0,15.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10,355.0,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-11,470.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12,459.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### **Retention rate of customer**

In [26]:
# Calculate retention rate
cohort_sizes = cohort_pivot.iloc[:,0]
retention_matrix = cohort_pivot.divide(cohort_sizes, axis=0)

display(retention_matrix.round(3) * 100)

MonthSinceFirstPurchase,0,1,2,3,4,5,6,7,8,9,10,11
CohortMonth,,,,,,,,,,,,
2022-01,100.0,0.4,0.4,1.6,1.6,1.2,1.6,2.4,2.8,1.6,3.6,0.4
2022-02,100.0,1.9,0.9,2.3,0.5,0.9,3.3,2.3,2.3,2.3,1.4,NaN
2022-03,100.0,0.7,1.7,1.4,1.4,3.1,3.4,1.0,2.4,4.5,NaN,NaN
2022-04,100.0,0.4,1.9,0.8,1.2,1.9,1.2,2.3,2.7,NaN,NaN,NaN
2022-05,100.0,2.0,2.0,2.8,2.3,1.4,2.0,3.7,NaN,NaN,NaN,NaN
2022-06,100.0,1.2,3.3,2.5,1.2,1.2,3.3,NaN,NaN,NaN,NaN,NaN
2022-07,100.0,2.7,2.7,1.4,2.1,3.4,NaN,NaN,NaN,NaN,NaN,NaN
2022-08,100.0,2.9,2.0,1.4,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-09,100.0,1.7,2.9,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10,100.0,1.7,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-11,100.0,1.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- Initial Drop-off: For most cohorts, there's a significant drop in retention after the first month (Month 0 to Month 1). This is very common, as some customers might make a one-time purchase. For example, the January 2022 cohort drops from 100% to 0.4% retention in the first month.

- Varying Retention by Cohort: Some cohorts show slightly better initial retention than others. For instance, the February 2022 cohort has a 1.9% retention rate in Month 1, which is higher than January's 0.4%.

- Longer-term Retention: As time progresses, the retention rates generally continue to decrease, with most cohorts showing very low retention percentages after a few months. For example, by Month 7, the January cohort retains only 2.4% of its original customers.

### **Compare the retention rate between the Corporate and Consumer groups**

##### **Cohort Analysis for Corporate Segment**

In [34]:
# Check unique segments in df_cohort
segments = df_cohort['Segment'].unique()
print(f"Unique Segments: {segments}")

Unique Segments: ['Self-Employed' 'Corporate' 'Consumer']

In [35]:
# Filter df_cohort for Corporate segment
df_cohort_corporate = df_cohort[df_cohort['Segment'] == 'Corporate'].copy()

# Calculate MonthSinceFirstPurchase for Corporate segment
df_cohort_corporate.loc[:, 'MonthSinceFirstPurchase'] = (df_cohort_corporate['OrderMonth'].dt.year - df_cohort_corporate['CohortMonth'].dt.year) * 12 + \
                                                 (df_cohort_corporate['OrderMonth'].dt.month - df_cohort_corporate['CohortMonth'].dt.month)

# Group by CohortMonth and MonthSinceFirstPurchase to count unique customers for Corporate segment
cohort_counts_corporate = df_cohort_corporate.groupby(['CohortMonth', 'MonthSinceFirstPurchase'])['CustomerID'].nunique().reset_index()

# Create the pivot table for Corporate segment
cohort_pivot_corporate = cohort_counts_corporate.pivot_table(index='CohortMonth', columns='MonthSinceFirstPurchase', values='CustomerID')

# Calculate retention rate for Corporate segment
cohort_sizes_corporate = cohort_pivot_corporate.iloc[:,0]
retention_matrix_corporate = cohort_pivot_corporate.divide(cohort_sizes_corporate, axis=0)

print("Corporate Segment Retention Matrix:")
display(retention_matrix_corporate.round(3) * 100)

Corporate Segment Retention Matrix:

MonthSinceFirstPurchase,0,1,2,3,4,5,6,7,8,9,10
CohortMonth,,,,,,,,,,,
2022-01,100.0,NaN,1.2,1.2,1.2,1.2,2.4,2.4,3.6,1.2,3.6
2022-02,100.0,2.9,NaN,1.5,1.5,NaN,1.5,4.4,NaN,NaN,1.5
2022-03,100.0,2.6,1.3,1.3,1.3,2.6,1.3,NaN,2.6,2.6,NaN
2022-04,100.0,NaN,1.4,1.4,1.4,2.7,NaN,1.4,2.7,NaN,NaN
2022-05,100.0,4.3,4.3,2.1,5.3,3.2,3.2,5.3,NaN,NaN,NaN
2022-06,100.0,0.6,5.7,3.2,0.6,0.6,1.3,NaN,NaN,NaN,NaN
2022-07,100.0,2.1,2.1,2.1,2.1,5.3,NaN,NaN,NaN,NaN,NaN
2022-08,100.0,2.9,2.9,2.2,2.2,NaN,NaN,NaN,NaN,NaN,NaN
2022-09,100.0,NaN,NaN,1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10,100.0,1.9,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-11,100.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Corporate Segment Retention Matrix:**

- Initial Drop-off: Similar to the overall cohort analysis, there's a significant drop after Month 0. For example, the January 2022 Corporate cohort drops from 100% to around 1.2% by Month 2, and some months even show no retention in Month 1.
- Varying Monthly Retention: Retention rates for the Corporate segment appear to fluctuate more month-to-month. Some months show slightly higher retention at later stages (e.g., Month 8 for Jan cohort is 3.6%).

##### **Cohort Analysis for Consumer Segment**

In [36]:
# Filter df_cohort for Consumer segment
df_cohort_consumer = df_cohort[df_cohort['Segment'] == 'Consumer'].copy()

# Calculate MonthSinceFirstPurchase for Consumer segment
df_cohort_consumer.loc[:, 'MonthSinceFirstPurchase'] = (df_cohort_consumer['OrderMonth'].dt.year - df_cohort_consumer['CohortMonth'].dt.year) * 12 + \
                                               (df_cohort_consumer['OrderMonth'].dt.month - df_cohort_consumer['CohortMonth'].dt.month)

# Group by CohortMonth and MonthSinceFirstPurchase to count unique customers for Consumer segment
cohort_counts_consumer = df_cohort_consumer.groupby(['CohortMonth', 'MonthSinceFirstPurchase'])['CustomerID'].nunique().reset_index()

# Create the pivot table for Consumer segment
cohort_pivot_consumer = cohort_counts_consumer.pivot_table(index='CohortMonth', columns='MonthSinceFirstPurchase', values='CustomerID')

# Calculate retention rate for Consumer segment
cohort_sizes_consumer = cohort_pivot_consumer.iloc[:,0]
retention_matrix_consumer = cohort_pivot_consumer.divide(cohort_sizes_consumer, axis=0)

print("Consumer Segment Retention Matrix:")
display(retention_matrix_consumer.round(3) * 100)

Consumer Segment Retention Matrix:

MonthSinceFirstPurchase,0,1,2,3,4,5,6,7,8,9,10,11
CohortMonth,,,,,,,,,,,,
2022-01,100.0,NaN,NaN,NaN,0.8,1.6,0.8,3.3,3.3,1.6,2.5,0.8
2022-02,100.0,1.8,1.8,3.6,NaN,1.8,4.5,1.8,1.8,3.6,1.8,NaN
2022-03,100.0,NaN,2.0,1.3,2.0,3.3,5.2,1.3,2.0,5.2,NaN,NaN
2022-04,100.0,0.8,1.6,0.8,0.8,1.6,2.3,2.3,3.1,NaN,NaN,NaN
2022-05,100.0,1.0,1.0,3.5,1.5,0.5,2.0,3.5,NaN,NaN,NaN,NaN
2022-06,100.0,1.7,2.9,2.1,2.1,1.2,5.0,NaN,NaN,NaN,NaN,NaN
2022-07,100.0,2.9,2.2,1.5,2.2,3.7,NaN,NaN,NaN,NaN,NaN,NaN
2022-08,100.0,2.2,0.9,1.3,1.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-09,100.0,2.8,3.6,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10,100.0,1.7,1.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-11,100.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Consumer Segment Retention Matrix:**

- Initial Drop-off: The Consumer segment also experiences a sharp initial drop. The January 2022 Consumer cohort, for instance, has a NaN for Month 1, then shows 0.8% retention in Month 4, indicating a very low initial engagement post-acquisition.
- Relatively Consistent, but Low, Retention: After the initial drop, the retention rates tend to remain very low, often below 5% for most cohorts across the subsequent months.

**Comparison Insights:**

- Low Overall Retention for Both: Both Corporate and Consumer segments show generally low retention rates, suggesting a common challenge in customer engagement after the first purchase.
- Corporate vs. Consumer Early Retention: There doesn't appear to be a consistently clear winner in early retention (Month 1-3). Some Corporate cohorts show slightly better early retention, while others have NaN values, indicating zero retained customers in those early months. Consumer cohorts also show similar patterns.
- Data Sparsity: Many cells in both matrices show NaN values, especially in later months for various cohorts. This could mean either zero retained customers or simply that the data period for those specific cohort-month combinations has not yet occurred or is too small to show a value. This makes it harder to draw definitive long-term conclusions.

### **Cohort Analysis by Annual Income**

In [37]:
# Display description of AnnualIncome in df_customer to determine bins
display(df_customer['AnnualIncome'].describe())

count     17415.000000
mean      57190.927361
std       32213.237506
min       10000.000000
25%       30000.000000
50%       60000.000000
75%       70000.000000
max      170000.000000
Name: AnnualIncome, dtype: float64

From the description, the annual income ranges from 10,000 to 170,000, with a mean of around 57,000. I'll create income groups using these quantiles:

In [40]:
# Define income bins and labels based on quantiles and domain knowledge
income_bins = [0, 30000, 60000, 90000, 120000, df_customer['AnnualIncome'].max()]
income_labels = ['Low Income (0-30k)', 'Mid Income (30k-60k)', 'Upper-Mid Income (60k-90k)', 'High Income (90k-120k)', 'Very High Income (>120k)']

# Create 'IncomeGroup' column in df_customer
df_customer['IncomeGroup'] = pd.cut(df_customer['AnnualIncome'], bins=income_bins, labels=income_labels, right=False)

# Merge 'IncomeGroup' into df_cohort
df_cohort_income = pd.merge(df_cohort, df_customer[['CustomerID', 'IncomeGroup']], on='CustomerID', how='left')

# Display the first few rows with the new IncomeGroup
display(df_cohort_income.head())

,RowID,OrderID,OrderDate,CustomerID,Segment,RegionCode,ProductCode,Quantity,Sales,Discount,...,Gender,EmailAddress,AnnualIncome,EducationLevel,Occupation,HomeOwner,CohortMonth,OrderMonth,MonthSinceFirstPurchase,IncomeGroup
0,28882,IN-2014-SU206651-41899,2022-09-17,SU-206651,Self-Employed,R0003,P000004,4,556,0.0,...,F,christy12@hotmail.com,70000,Bachelors,Professional,N,2022-09,2022-09,0,Upper-Mid Income (60k-90k)
1,24294,IN-2014-JM156551-41905,2022-09-23,JM-156551,Corporate,R0003,P000017,15,735,0.0,...,F,jacquelyn20@hotmail.com,70000,Bachelors,Professional,N,2022-09,2022-09,0,Upper-Mid Income (60k-90k)
2,29494,IN-2014-LO171701-41906,2022-09-24,LO-171701,Corporate,R0003,P000018,12,336,0.0,...,M,curtis9@hotmail.com,60000,Bachelors,Professional,Y,2022-09,2022-09,0,Upper-Mid Income (60k-90k)
3,21399,IN-2014-VW217751-41901,2022-09-19,VW-217751,Corporate,R0004,P000027,8,80,0.0,...,M,clarence32@hotmail.com,30000,Partial College,Clerical,Y,2022-09,2022-09,0,Mid Income (30k-60k)
4,29493,IN-2014-LO171701-41906,2022-09-24,LO-171701,Corporate,R0003,P000028,12,816,0.0,...,M,curtis9@hotmail.com,60000,Bachelors,Professional,Y,2022-09,2022-09,0,Upper-Mid Income (60k-90k)

In [41]:
for group in income_labels:
    print(f"\n--- Cohort Analysis for Income Group: {group} ---")

    df_current_income_group = df_cohort_income[df_cohort_income['IncomeGroup'] == group].copy()

    if df_current_income_group.empty:
        print("No data for this income group.")
        continue

    # Calculate MonthSinceFirstPurchase (already exists in df_cohort_income, but re-calculate for safety)
    # df_current_income_group.loc[:, 'MonthSinceFirstPurchase'] = (df_current_income_group['OrderMonth'].dt.year - df_current_income_group['CohortMonth'].dt.year) * 12 + \
    #                                                        (df_current_income_group['OrderMonth'].dt.month - df_current_income_group['CohortMonth'].dt.month)

    # Group by CohortMonth and MonthSinceFirstPurchase to count unique customers
    cohort_counts_income = df_current_income_group.groupby(['CohortMonth', 'MonthSinceFirstPurchase'])['CustomerID'].nunique().reset_index()

    # Create the pivot table for the current income group
    cohort_pivot_income = cohort_counts_income.pivot_table(index='CohortMonth', columns='MonthSinceFirstPurchase', values='CustomerID')

    # Calculate retention rate for the current income group
    cohort_sizes_income = cohort_pivot_income.iloc[:,0]
    retention_matrix_income = cohort_pivot_income.divide(cohort_sizes_income, axis=0)

    display(retention_matrix_income.round(3) * 100)

--- Cohort Analysis for Income Group: Low Income (0-30k) ---

MonthSinceFirstPurchase,0,1,2,3,4,5,6,7,8,9,10
CohortMonth,,,,,,,,,,,
2022-01,100.0,NaN,NaN,3.2,3.2,NaN,3.2,6.5,9.7,3.2,3.2
2022-02,100.0,NaN,NaN,6.9,NaN,NaN,3.4,3.4,3.4,3.4,NaN
2022-03,100.0,NaN,2.2,NaN,NaN,6.7,2.2,2.2,6.7,4.4,NaN
2022-04,100.0,NaN,NaN,NaN,NaN,2.5,2.5,2.5,2.5,NaN,NaN
2022-05,100.0,1.8,NaN,3.6,NaN,3.6,3.6,9.1,NaN,NaN,NaN
2022-06,100.0,1.2,2.4,NaN,NaN,NaN,2.4,NaN,NaN,NaN,NaN
2022-07,100.0,2.0,2.0,3.9,NaN,2.0,NaN,NaN,NaN,NaN,NaN
2022-08,100.0,5.5,2.7,2.7,1.4,NaN,NaN,NaN,NaN,NaN,NaN
2022-09,100.0,NaN,2.1,5.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10,100.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-11,100.0,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Cohort Analysis for Income Group: Mid Income (30k-60k) ---

MonthSinceFirstPurchase,0,1,2,3,4,5,6,7,8,9,10
CohortMonth,,,,,,,,,,,
2022-01,100.0,NaN,NaN,2.6,1.3,2.6,NaN,1.3,2.6,3.9,2.6
2022-02,100.0,3.1,NaN,3.1,1.5,1.5,6.2,4.6,NaN,1.5,1.5
2022-03,100.0,NaN,2.3,NaN,NaN,1.2,5.8,NaN,NaN,7.0,NaN
2022-04,100.0,NaN,1.3,NaN,NaN,1.3,NaN,3.8,3.8,NaN,NaN
2022-05,100.0,1.8,3.5,3.5,4.4,0.9,2.7,2.7,NaN,NaN,NaN
2022-06,100.0,1.4,4.9,2.8,1.4,1.4,2.1,NaN,NaN,NaN,NaN
2022-07,100.0,1.2,2.3,NaN,1.2,2.3,NaN,NaN,NaN,NaN,NaN
2022-08,100.0,4.1,2.4,0.8,3.3,NaN,NaN,NaN,NaN,NaN,NaN
2022-09,100.0,2.8,3.4,4.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10,100.0,3.8,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-11,100.0,2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Cohort Analysis for Income Group: Upper-Mid Income (60k-90k) ---

MonthSinceFirstPurchase,0,1,2,3,4,5,6,7,8,9,10,11
CohortMonth,,,,,,,,,,,,
2022-01,100.0,0.9,0.9,0.9,0.9,NaN,2.8,2.8,1.9,NaN,3.7,0.9
2022-02,100.0,2.2,2.2,1.1,NaN,NaN,2.2,1.1,3.4,2.2,2.2,NaN
2022-03,100.0,1.7,0.9,2.6,1.7,4.3,3.4,1.7,3.4,2.6,NaN,NaN
2022-04,100.0,1.0,3.8,1.9,1.9,2.9,1.9,1.0,2.9,NaN,NaN,NaN
2022-05,100.0,2.4,0.8,1.6,0.8,1.6,1.6,1.6,NaN,NaN,NaN,NaN
2022-06,100.0,1.0,2.4,2.4,1.0,1.0,4.3,NaN,NaN,NaN,NaN,NaN
2022-07,100.0,3.4,3.4,0.8,4.2,4.2,NaN,NaN,NaN,NaN,NaN,NaN
2022-08,100.0,2.5,1.9,1.2,1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-09,100.0,1.4,2.4,1.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10,100.0,0.7,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-11,100.0,1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Cohort Analysis for Income Group: High Income (90k-120k) ---

MonthSinceFirstPurchase     0    1    2    3    4    5    6    7    9    10
CohortMonth
2022-01                  100.0  NaN  NaN  NaN  NaN  4.2  NaN  NaN  NaN  4.2
2022-02                  100.0  NaN  NaN  NaN  NaN  6.7  NaN  NaN  6.7  NaN
2022-03                  100.0  NaN  NaN  NaN  3.7  NaN  NaN  NaN  3.7  NaN
2022-04                  100.0  NaN  NaN  NaN  4.5  NaN  NaN  4.5  NaN  NaN
2022-05                  100.0  2.9  5.9  2.9  5.9  NaN  NaN  5.9  NaN  NaN
2022-06                  100.0  NaN  2.1  2.1  2.1  2.1  2.1  NaN  NaN  NaN
2022-07                  100.0  7.4  3.7  3.7  NaN  3.7  NaN  NaN  NaN  NaN
2022-08                  100.0  NaN  1.9  NaN  1.9  NaN  NaN  NaN  NaN  NaN
2022-09                  100.0  4.7  4.7  4.7  NaN  NaN  NaN  NaN  NaN  NaN
2022-10                  100.0  NaN  3.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2022-11                  100.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2022-12                  100.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

--- Cohort Analysis for Income Group: Very High Income (>120k) ---

MonthSinceFirstPurchase,0,1,2,3,4,5,6,7,8,9,10
CohortMonth,,,,,,,,,,,
2022-01,100.0,NaN,NaN,NaN,7.7,NaN,NaN,NaN,NaN,NaN,7.7
2022-02,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.1,NaN,NaN
2022-03,100.0,NaN,7.1,7.1,7.1,NaN,NaN,NaN,NaN,7.1,NaN
2022-04,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-05,100.0,NaN,NaN,4.8,NaN,NaN,NaN,4.8,NaN,NaN,NaN
2022-06,100.0,3.6,7.1,10.7,3.6,3.6,7.1,NaN,NaN,NaN,NaN
2022-07,100.0,NaN,NaN,NaN,NaN,12.5,NaN,NaN,NaN,NaN,NaN
2022-08,100.0,NaN,NaN,3.2,3.2,NaN,NaN,NaN,NaN,NaN,NaN
2022-09,100.0,NaN,4.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10,100.0,NaN,4.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-11,100.0,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Overall Trend:**

- Initial Drop-off: Consistent with the overall and segment-specific analyses, all income groups experience a significant drop in retention immediately after the first purchase (Month 0 to Month 1). This indicates that many customers across all income levels make a single purchase.
- Low Long-Term Retention: Generally, long-term retention remains quite low across all income brackets. Very few customers continue to make purchases after the first few months.

**Comparison by Income Group:**

- Low Income (0-30k) & Mid Income (30k-60k): These groups show very similar patterns of low and often sporadic retention after the initial month. There isn't a clear advantage in sustainability between these two groups.
- Upper-Mid Income (60k-90k): While still facing an initial drop, this group sometimes exhibits slightly more consistent, albeit still low, retention in later months compared to the lower income groups. They might have a marginally better likelihood of repeat purchases over a longer period.
- High Income (90k-120k) & Very High Income (>120k): For these higher income brackets, the retention rates in later months (e.g., Month 4 onwards) appear to be slightly more stable or show higher percentages in some instances, though the absolute numbers of retained customers remain small. This suggests that while fewer in number, customers in these higher income groups might have a slightly higher propensity for longer-term engagement once they pass the initial drop-off phase. However, the data can be sparse for these groups in later months, making definitive conclusions challenging.

**Conclusion on Most Sustainable Group:**

- Based on the analysis, customers in the Upper-Mid Income (60k-90k), High Income (90k-120k), and Very High Income (>120k) groups tend to show a marginally more sustainable retention pattern compared to the lower income groups, particularly in the later months. While overall retention is low for everyone, the higher income groups appear to have a slightly better, albeit still fragile, long-term engagement. This indicates that efforts to foster loyalty might yield better returns in these segments, as they show a slightly higher propensity for continued interaction after the initial purchase.

**It's important to note that the retention numbers are generally very low for all groups, suggesting a broader challenge in customer retention that extends beyond just income levels.**